export const books = [
  {
    id: 0,
    title: "Bridge to Terabithia",
    author: "Peter Paul",
    image: require("./images/book1.png"),
    price: 5.6,
    quantity: 4,
    isLiked: false,
  },
  {
    id: 1,
    title: "Love Unscripted",
    author: "Owen Nicholls",
    image: require("./images/book2.png"),
    price: 4.8,
    quantity: 4,
    isLiked: false,
  },
  {
    id: 2,
    title: "A Desolation",
    author: "Katherine Peterson",
    image: require("./images/book3.png"),
    price: 5.0,
    quantity: 4,
    isLiked: false,
  },
  {
    id: 3,
    title: "Shuri",
    author: "Viola Davis",
    image: require("./images/book4.png"),
    price: 8.5,
    quantity: 4,
    isLiked: false,
  },
];
